# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# Warnings currently triggered by the code.
# These may or may not be code we want to fix.
- ignore: {name: "Eta reduce"} # 7 hints
- ignore: {name: "Functor law"} # 1 hint
- ignore: {name: "Fuse concatMap/map"} # 1 hint
- ignore: {name: "Redundant $"} # 1 hint
- ignore: {name: "Redundant $!"} # 8 hints
- ignore: {name: "Redundant bracket"} # 6 hints
- ignore: {name: "Redundant flip"} # 2 hints
- ignore: {name: "Redundant fmap"} # 2 hints
- ignore: {name: "Replace case with fromMaybe"} # 1 hint
- ignore: {name: "Unused LANGUAGE pragma"} # 12 hints
- ignore: {name: "Use ++"} # 5 hints
- ignore: {name: "Use <&>"} # 1 hint
- ignore: {name: "Use fewer imports"} # 2 hints
- ignore: {name: "Use maybe"} # 5 hints
- ignore: {name: "Use newtype instead of data"} # 15 hints
- ignore: {name: "Use section"} # 1 hint
- ignore: {name: "Use traverse_"} # 1 hint
